const SET_CART = 'SET_CART';
const DELETE_PRODUCT = 'DELETE_PRODUCT';
const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
const APPLY_DISCOUNT = 'APPLY_DISCOUNT';


export {
  SET_CART,
  DELETE_PRODUCT,
  UPDATE_QUANTITY,
  ADD_PRODUCT_TO_CART,
  APPLY_DISCOUNT
}